"""тг айдишник

Revision ID: d569afb66942
Revises: bc33814cb0a0
Create Date: 2026-03-24 22:14:05.948734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd569afb66942'
down_revision: Union[str, Sequence[str], None] = 'bc33814cb0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_user_id', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_column('users', 'tg_user_id')
    # ### end Alembic commands ###
